language: perl
matrix:
 include:
  - perl: "5.30"
    dist: xenial
  - perl: "5.26"
    dist: xenial
  - perl: "5.22"
    dist: xenial
  - perl: "5.20"
    dist: trusty
  - perl: "5.18"
    dist: trusty
  - perl: "5.16"
    dist: trusty
  - perl: "5.14"
    dist: trusty
  - perl: "5.12"
    dist: trusty
  - perl: "5.10"
    dist: trusty
  - perl: "5.8"
    dist: trusty
  # The perl does not matter here, system perl will be used
  - perl: "5.18"
    os: osx
    osx_image: xcode12.2
    sudo: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install cpanminus; fi

install:
  # For system perls, this step shouldn't do anything
  # (all requirements are already met with system packages)
  # On OSX the system perl already comes with DateTime
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cpanm --sudo --quiet --installdeps --notest .; else cpanm --quiet --installdeps --notest .; fi

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
sudo: false
